modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Low-Drag-MC/ShimmerFire/issues" #optional

[[mods]] #mandatory
modId="shimmerfire" #mandatory
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Shimmer Fire" #mandatory
logoFile="icon.png" #optional
displayURL="https://github.com/Low-Drag-MC/ShimmerFire"
# A text field displayed in the mod UI
credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="KilaBash, zomb676, Mosquitozzi" #optional
description='''ShimemrFire, a Teacon22 demo mod.'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.shimmerfire]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.shimmerfire]]
    modId="shimmerfire"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.shimmerfire]]
    modId="multiblocked"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[0.9.5,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.shimmerfire]]
    modId="geckolib3"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[3.0.18,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.shimmerfire]]
    modId="shimmer"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[0.1.6,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.shimmerfire]]
    modId="nocaet"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="BEFORE"
    side="BOTH"